version: '3.8'
services:
  govietnam-website:
    image: govietnam-website:latest
    container_name: govietnam-website
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
    restart: always
